version: '3'

services:
  nx-app-base:
    container_name: f_nx-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEV_PLATFORM=DOCKER
    ports:
      - 3010:3010
      - 9229:9229
    #    volumes:
    #      - ./:/app
    ##      - ./node_modules:/app/node_modules
    networks:
      - fbn
networks:
  fbn:
    driver: bridge
