version: '3.1'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    #    volumes:
    #      - /data/postgres:/data/postgres
    env_file:
      - ./envs/.db.env
    networks:
      - fbn

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '8443:443'
      - '8080:80'
    #    volumes:
    #      - /data/pgadmin:/root/.pgadmin
    env_file:
      - ./envs/.db.env
    networks:
      - fbn

  rabbitmq3:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - '15672:15672'
      - '5672:5672'
    networks:
      - fbn

networks:
  fbn:
    driver: bridge
